### ISSUE TITLE
about train time

### ISSUE THREAD

**Issue by fj6833** [dominickrei/PoseAwareVT#2]
Hello author, if I want to train on the smart home dataset, what GPU do I need at least and how long do I need to train？

**Comment by dominickrei** [comment]
Hello, thank you for your interest. We train most of our models using 8 NVIDIA RTX A5000 GPUs and it takes 0.5-1.5 hours to train depending on the dataset. Any GPU with CUDA capability should work but you may have to change the [batch size used for training](https://github.com/dominickrei/PoseAwareVT/blob/87973675152d771392f660837fa2a4f4231fb734/configs/PAAT_SH_CS.yaml#L5). Training time will vary depending on the dataset.
